#!/bin/sh

eval `/opt/SUNWsamfs/bin/sls -D $1 | awk '{ getline; getline; size=$2; getline;
					 mode = "r"; if ($1 == "offline;") {
					 	mode="m";
					} else if ($1 == "archdone;") {
						mode="p";
					}
					print "mode="mode" size="size; exit}'`
		
		

echo $mode $size

